# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athena', '0002_ehr_times_interaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ehr_times',
            name='location',
            field=models.CharField(default=b'0', max_length=200),
        ),
        migrations.AddField(
            model_name='ehr_times',
            name='status',
            field=models.CharField(default=b'0', max_length=200),
        ),
        migrations.AddField(
            model_name='rtls_times',
            name='location',
            field=models.CharField(default=b'0', max_length=200),
        ),
        migrations.AddField(
            model_name='rtls_times',
            name='status',
            field=models.CharField(default=b'0', max_length=200),
        ),
        migrations.AlterField(
            model_name='ehr_times',
            name='times',
            field=models.DateTimeField(verbose_name=b'athena time'),
        ),
        migrations.AlterField(
            model_name='rtls_times',
            name='times',
            field=models.DateTimeField(verbose_name=b'rivER time'),
        ),
    ]
